CATALOGUE_HOST: catalogue.adithyaprakash.online
USER_HOST: user.adithyaprakash.online
SHIPPING_HOST: shipping.adithyaprakash.online
CART_HOST: cart.adithyaprakash.online
PAYMENT_HOST: payment.adithyaprakash.online